version: "3.3"
services:
  mysql:
    container_name: dattebayo-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=dattebayo
      - MYSQL_DATABASE=dattebayo
      - MYSQL_USER=dattebayo
      - MYSQL_PASSWORD=dattebayo
    image: "mysql:latest"

  mysql_shadow:
    container_name: dattebayo-db-shadow
    ports:
      - "3307:3307"
    environment:
      - MYSQL_ROOT_PASSWORD=dattebayo
      - MYSQL_DATABASE=dattebayo
      - MYSQL_USER=dattebayo
      - MYSQL_PASSWORD=dattebayo
    image: "mysql:latest"
