export const Kiri = ({ className }) => {
  return (
    <svg className={className} xmlns="http://www.w3.org/2000/svg" viewBox="0 0 125 100" version="1">
      <path
        d="M18.026 40.356C43.632 26.833 28.834 18.79 54.931 5.038"
        style={{ marker: "none" }}
        fillOpacity="1"
        fillRule="evenodd"
        strokeDasharray="none"
        strokeDashoffset="0"
        strokeLinecap="round"
        strokeLinejoin="miter"
        strokeMiterlimit="4"
        strokeOpacity="1"
        strokeWidth="8"
        markerEnd="none"
        markerMid="none"
        markerStart="none"
        color="#000"
        display="inline"
        enableBackground="accumulate"
        opacity="1"
        overflow="visible"
        visibility="visible"
      ></path>
      <path
        d="M4.592 95.385C30.197 81.862 15.4 73.82 41.496 60.067"
        style={{ marker: "none" }}
        fill="none"
        fillOpacity="1"
        fillRule="evenodd"
        strokeDasharray="none"
        strokeDashoffset="0"
        strokeLinecap="round"
        strokeLinejoin="miter"
        strokeMiterlimit="4"
        strokeOpacity="1"
        strokeWidth="8"
        markerEnd="none"
        markerMid="none"
        markerStart="none"
        color="#000"
        display="inline"
        enableBackground="accumulate"
        opacity="1"
        overflow="visible"
        visibility="visible"
      ></path>
      <path
        d="M83.997 40.006c25.606-13.523 10.808-21.564 36.905-35.317"
        style={{ marker: "none" }}
        fill="none"
        fillOpacity="1"
        fillRule="evenodd"
        strokeDasharray="none"
        strokeDashoffset="0"
        strokeLinecap="round"
        strokeLinejoin="miter"
        strokeMiterlimit="4"
        strokeOpacity="1"
        strokeWidth="8"
        markerEnd="none"
        markerMid="none"
        markerStart="none"
        color="#000"
        display="inline"
        enableBackground="accumulate"
        opacity="1"
        overflow="visible"
        visibility="visible"
      ></path>
      <path
        d="M70.26 95.036c25.605-13.523 10.808-21.565 36.904-35.318"
        style={{ marker: "none" }}
        fill="none"
        fillOpacity="1"
        fillRule="evenodd"
        strokeDasharray="none"
        strokeDashoffset="0"
        strokeLinecap="round"
        strokeLinejoin="miter"
        strokeMiterlimit="4"
        strokeOpacity="1"
        strokeWidth="8"
        markerEnd="none"
        markerMid="none"
        markerStart="none"
        color="#000"
        display="inline"
        enableBackground="accumulate"
        opacity="1"
        overflow="visible"
        visibility="visible"
      ></path>
    </svg>
  );
};
